### ISSUE TITLE
NULL domain for analyses 705-712

### ISSUE THREAD

**Issue by jreps** [OHDSI/FeatureExtraction#264]
705 to 712 in https://github.com/OHDSI/FeatureExtraction/blob/main/inst/csv/PrespecAnalyses.csv do not have a domain.  Is there a reason for the domain not being Measurement?

**Comment by anthonysena** [comment]
These entries in the [PrespecAnalyses.csv#L70-L77](https://github.com/OHDSI/FeatureExtraction/blob/main/inst/csv/PrespecAnalyses.csv#L70-L77) do not specify a domain since these analyses have SQL specific to the measurement domain and so do not require the domain as a parameter to pass into the SQL.
