### ISSUE TITLE
Distribution values for time at risk, prior observation, post observation

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/FeatureExtraction#31]
I wasn't able to find code in version_2 about creating distributions for time at risk (cohort_start->cohort_end), prior observation (op_start -> cohort_start) or post observation (cohort_start->op_end).  We'd want to generate the quartile ranges (including min, p10, p25, median, p75, p90, max) for these continuous values.

**Comment by schuemie** [comment]
Please see analyses 8-10: https://github.com/OHDSI/FeatureExtraction/blob/version_2/inst/csv/PrespecAnalyses.csv#L9

**Comment by chrisknoll** [comment]
Thank you, @schuemie .

**Comment by alondhe** [comment]
In order to enable these for Atlas, we could either set analyses 8-10 as "default" choices in that CSV or explicitly augment the defaults provided via getDefaultPrespecAnalyses. I'm fine with implementing either approach, but @schuemie wanted to get your input.

**Comment by schuemie** [comment]
We can't set them to default in the CSV because they are not appropriate baseline characteristics (some look into the future), so for example should not be used in predictive models.

There is no reason ATLAS should stick to the default set, you can make your own selection from the prespecified analyses.
