### ISSUE TITLE
createCovariateSettings error

### ISSUE THREAD

**Issue by jamieweaver** [OHDSI/FeatureExtraction#4]
I get the following error when useCovariateMeasurementBelow is set to true: execute JDBC update query failed in dbSendUpdate (Invalid object name '#cov_m_below'.).  createCovariateSettings runs fine when I set measurement covariates to FALSE. I haven't tested to see if this is the only problematic measurement covariate.

**Comment by MaximMoinat** [comment]
Hello Jamie, I just got the same error and maybe found the problem. 
If I understand the sql (/inst/sql/sql_server/GetCovariates.sql), the problem occurs when there are no measurements to put in the temporary #cov_m_below table. For me, the problem was fixed after removing the ids given to the 'includedCovariateConceptIds' option of the createCovariateSettings function.

Could you check whether a similar issue could cause the problem in your case?

**Comment by schuemie** [comment]
Hi @jamieweaver and @MaximMoinat ,

Could you tell me if this [latest commit](https://github.com/OHDSI/FeatureExtraction/commit/b05c129e71336af2757bc5cc4797733881fc236a) fixed this problem?

**Comment by MaximMoinat** [comment]
Yes, my problem seems to be fixed. 
However, I can't replicate the problem again by installing a previous release.
