### ISSUE TITLE
What is the purpose of this code in the covariate settings builders?

### ISSUE THREAD

**Issue by sirpoovey** [OHDSI/FeatureExtraction#6]
As far as I can tell this code is unnecessary as the code preceding it already creates a list out of the function parameters

https://github.com/OHDSI/FeatureExtraction/blob/master/R/GetDefaultCovariates.R#L517-L521

I would also be interested in getting clarity as to why the covariateSettings builders take a long list of function parameters, stitches them into a list, and then explode them when passing them to loadRenderTranslateSql.  Is the reason just to reduce the number of parameters on the getCovariateData functions? 

https://github.com/OHDSI/FeatureExtraction/blob/master/R/GetDefaultCovariates.R#L90-L152

**Comment by schuemie** [comment]
Hi @sirpoovey ,

The first bit of code gets the default values of the function, as specified in the function definition. The second bit of code replaces the default values with any values the user may have specified when calling the function. Without the second bit of code, the ```covariateSettings``` object would always have exactly the same values: the ones specified in the function definition.

The reason for having a separate parameter object (```covariateSettings```) is threefold:

1. For clarity, so you don't have so many arguments when calling the ```getCovariateData``` functions.

2. Because the ```FeatureExtraction``` package is often used inside other packages, such as [CohortMethod](https://github.com/OHDSI/CohortMethod) and [PatientLevelPrediction](https://github.com/OHDSI/PatientLevelPrediction), where the ```getCovariateData``` function is called  from within another function, like [```getDbCohortMethodData```](https://github.com/OHDSI/CohortMethod/blob/master/R/DataLoadingSaving.R#L120), where the ```covariateSettings``` object can be passed to that function so it can pass it on to the ```getCovariateData``` function.

3. So you can have different ```covariateSettings``` objects for different covariate builders, but one main ```getCovariateData``` function. This mean you can call this function with different objects to get different behaviors, including [custom defined covariates](https://raw.githubusercontent.com/OHDSI/FeatureExtraction/master/inst/doc/CreatingCustomCovariateBuilders.pdf). This is most helpful in the context of point 2, where I can now feed any combination of ```covariateSettings``` objects to the ```getDbCohortMethodData``` function, and all relevant covariates will be constructed.

Hope this helps.

Cheers,
Martijn

**Comment by sirpoovey** [comment]
Hi Martijn,

Thanks for the clarification. As far as the first question the first half of the code will get the passed in values. The get() statement pulls from the passed in parameters. Just to confirm I ran it through a debugger with multiple argument lists and noted that the passed in values are set in the first part of the code. I propose we remove the second part of the code because I don't think it is necessary and the method it is using is quite confusing. 

As far as the second part that all makes sense. As I studied the code what it seems like we need is a language with object oriented features. The implementation of createCovariateSettings is quite general and could be used as the default constructor of a base class for covariateSettings. 

Also to address the part where we have a lot of parameters. I think with an OOP design we would just have a constructor that gives you an object with the defaults and then the package using that object (e.g. CohortMethod or PLP) would just override the defaults of the returned object. 

What are your thoughts on the above?

Thanks

**Comment by sirpoovey** [comment]
Hi Martin,

Thanks for the clarification. As far as the first question the first half of the code will get the passed in values. The get() statement pulls from the passed in parameters. Just to confirm I ran it through a debugger with multiple argument lists and noted that the passed in values are set in the first part of the code. I propose we remove the second part of the code because I don't think it is necessary and the method it is using is quite confusing. 

As far as the second part that all makes sense. As I studied the code what it seems like we need is a language with object oriented features. The implementation of createCovariateSettings is quite general and could be used as the default constructor of a base class for covariateSettings. 

Also to address the part where we have a lot of parameters. I think with an OOP design we would just have a constructor that gives you an object with the defaults and then the package using that object (e.g. CohortMethod or PLP) would just override the defaults of the returned object. 

What are your thoughts on the above?

Thanks

**Comment by schuemie** [comment]
Hi Jason,

You're right! The first part does already get the actual values. We can try to see if the code works without the second part (with R you never know).

I would love to follow a full OOP design, but my experience so far with R is that its OOP support is pretty lame. Inheritance, overriding, overloading, non of it is fully supported and definitely not enforced, so bugs are likely. I'm inclined to follow [Google's R Style Guide](https://google.github.io/styleguide/Rguide.xml) that states "avoid S4 objects and methods when possible; never mix S3 and S4". S3 is too informal to call OOP, and to be honest I haven't looked into R5 (nor have I ever seen it used). My hope is that one day we can cut over to [Julia](http://julialang.org/) when it is mature enough ;-)

Cheers,
Martijn
