### ISSUE TITLE
time_id is null in Demographic covariates for temporal covariates

### ISSUE THREAD

**Issue by chandryou** [OHDSI/FeatureExtraction#62]
I found that time_ids of demographic covariates created by temporal setting are nulls in current version of feature extraction package. 
In this case, CIReNN module in PLP cannot work (because timeId is null)..

**Comment by schuemie** [comment]
Hi Chan! 

Yes, that is intentional (the demographics typically do not pertain to a particular time window).

Would it be possible to modify CIReNN to work with the NULL values? (Maybe convert them to whatever CIReNN expects just prior to fitting?)

**Comment by jreps** [comment]
I can modify the way the data get mapped.  I'm not sure how best to include non-temporal data into the CIReNN though?  Should we have a non-temporal matrix (people by non-temporal features) in addition to the temporal tensor (people by time by temporal-features)?

**Comment by jreps** [comment]
Just spoke to Peter and he had a great idea.  How about rather than putting NULL as the time id for demographics, having the demographics for each time id and for things like age, make that days and have that as the actual value on the time id setting.  Does that make sense?

**Comment by chandryou** [comment]
@jreps , That's just what I've thought! If so, I don't have nothing more.

**Comment by schuemie** [comment]
@jreps , we can definitely do that, but it would mean a huge increase in size of the covariateData objects because demographics tend to not be sparse. For example, every subject will get an age for every period, and every subject will get a gender for every period.

If all temporal algorithms require this, then we should do it at construction of the features. If only a few do, we should probably write a function that expands the current compact representation into this new large format only for those algorithms that need it.

**Comment by jreps** [comment]
I was thinking, I can do it when I convert the data into the array, I'll update the plp code and test next week
