### ISSUE TITLE
Feature Extraction - Temporal covariates?

### ISSUE THREAD

**Issue by SSMK-wq** [OHDSI/FeatureExtraction#88]
Hello,

I was going through the **feature extraction package manual** and came to know about `create temporal covariates` function. But may i kindly check with you on the documentation?

```
settings <- createTemporalCovariateSettings(useConditionOccurrence = TRUE,
useMeasurementValue = TRUE)
In this case we’ve chosen to create binary covariates for each concept in the condition_occurrence table,
and continuous covariates for each measurement - unit combination in the measurement table in the CDM.
By default, temporal covariates are created for each day separately in the 365 days before (but not including)
the cohort start date. Different time windows can also be specified, for example creating 7 day intervals
instead:
```

1) If you see the highlighted info, it says **condition_occurrence covariates is binary**. Even though the we have set `TRUE` for the create Temporal covariates? As the **condition_occurrence values are non-numeric, it will only give us binary covariates?** Is there anyway to get **how many times a specific code has occurred in this patient's journey before cohort start date**? If we look at short term, medium term and long term, we still get binary covariates but do we get the no of times a specific code has occurred prior to cohort start date?

2) I see for measurement table we have continuous covariates. Meaning what does continuous covariates mean? Let's say a patient has Systolic blood pressure in his lab records. So will this result in multiple columns with percentile info like **SysBP_25pc, SysBP_50pc, SysBP_75pc** etc. Will it give summary statistics? Can you help me with an example please? I am trying to know how does the output look like.

**Comment by schuemie** [comment]
To answer question 1:
Temporal covariates are often still binary. By 'temporal' we mean the covariate capture window is cut into smaller intervals (by default single days). So instead of having a single covariate indicating whether a concept occurred in the last 365 days, we have 365 covariates, one for whether the concept occurred 365 days ago, one for whether it occurred 354 days ago, etc. 

We currently don't have covariates capturing how often a concept occurred.

To answer question 2:

You can create covariates either on a per-person basis, or by [aggregating them across your cohort](http://ohdsi.github.io/FeatureExtraction/articles/UsingFeatureExtraction.html#creating-aggregated-covariates-for-a-cohort-of-interest). On a per-person basis, the measurement covariates will contain the value of the last measurement before the end of the capture window. So if someone's sysBp was 120, the covariate will have the value 120. When aggregate, you will get the number you indicated, so min, max, 25th percentile, median, etc.
